# Usa una imagen base de Node.js
FROM node:18-alpine AS builder

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el package.json y el package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install --only=production

# Copia el código fuente de la aplicación
COPY . .

# Compila la aplicación
RUN npm run build

# Usa una imagen más ligera para producción
FROM node:18-alpine AS production

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia las dependencias desde la etapa anterior
COPY --from=builder /app/node_modules ./node_modules

# Copia la aplicación compilada
COPY --from=builder /app/dist ./dist

# Expone el puerto en el que la aplicación estará escuchando
EXPOSE 3000

# Define el comando por defecto para correr la aplicación
CMD ["node", "dist/main"]
