name: NestJS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - run: docker run -d -p 27017:27017 --name=mongo-example mongo:latest
    - run: yarn install
    - run: MONGODB_URI=mongodb://localhost:27017/taskmanagement && JWT_SECRET=hola && yarn run test:e2e